[package]
name = "kopperdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.56"
anyhow = "1.0.79"

[dev-dependencies]
rand = "0.8.5"
# plotters = "0.3.3" - to use stats
